
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 37;
  public static final int DISTINTO = 28;
  public static final int CTE_FLOAT = 23;
  public static final int RESTA = 36;
  public static final int CTE_STRING = 21;
  public static final int INT = 25;
  public static final int COR_CIERRA = 12;
  public static final int END_PROGRAM = 3;
  public static final int PAR_ABRE = 7;
  public static final int AND = 33;
  public static final int IGUAL = 27;
  public static final int MULTIPLICA = 38;
  public static final int COR_ABRE = 11;
  public static final int OR = 34;
  public static final int SUMA = 35;
  public static final int ASIGNA = 6;
  public static final int IF = 17;
  public static final int PUNTO_COMA = 14;
  public static final int ID = 20;
  public static final int EOF = 0;
  public static final int ENDDECLARE = 5;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int MENOR = 29;
  public static final int LLAVE_ABRE = 9;
  public static final int DECLARE = 4;
  public static final int MAYOR = 31;
  public static final int ELSE = 18;
  public static final int TAKE = 16;
  public static final int WHILE = 19;
  public static final int BEGIN_PROGRAM = 2;
  public static final int MAYOR_IGUAL = 32;
  public static final int FLOAT = 24;
  public static final int CTE_INT = 22;
  public static final int STRING = 26;
  public static final int LLAVE_CIERRA = 10;
  public static final int MENOR_IGUAL = 30;
  public static final int PAR_CIERRA = 8;
  public static final int PRINT = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN_PROGRAM",
  "END_PROGRAM",
  "DECLARE",
  "ENDDECLARE",
  "ASIGNA",
  "PAR_ABRE",
  "PAR_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COR_ABRE",
  "COR_CIERRA",
  "COMA",
  "PUNTO_COMA",
  "PRINT",
  "TAKE",
  "IF",
  "ELSE",
  "WHILE",
  "ID",
  "CTE_STRING",
  "CTE_INT",
  "CTE_FLOAT",
  "FLOAT",
  "INT",
  "STRING",
  "IGUAL",
  "DISTINTO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "SUMA",
  "RESTA",
  "DIVIDE",
  "MULTIPLICA"
  };
}

