// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: entrega_1/01-lexico_entrega_1.flex

package compilador;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import java_cup.runtime.*;
//import java_cup.sym; 

// Para escribir el archivo de la tabla de simbolos
import compilador.TablaSimbolos.*;



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\24\0\1\4"+
    "\5\0\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\11\16\1\17\1\20\1\21\1\22\1\23"+
    "\2\0\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\35\1\44\1\45\1\46\2\35\1\47\3\35"+
    "\1\50\1\0\1\51\1\0\1\52\1\0\32\35\1\53"+
    "\1\0\1\54\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\2\1\1\13\1\14"+
    "\1\1\1\15\10\16\1\17\1\20\1\21\1\22\1\0"+
    "\1\23\2\24\1\0\1\12\1\25\1\0\1\26\1\27"+
    "\1\30\1\31\4\16\1\32\3\16\2\24\1\0\1\12"+
    "\1\0\7\16\2\24\1\0\1\12\1\33\2\16\1\34"+
    "\1\0\2\16\1\35\1\16\1\24\2\0\1\12\2\16"+
    "\1\0\1\16\1\36\1\37\2\24\1\0\1\12\1\0"+
    "\1\16\1\0\1\16\2\24\1\0\1\12\1\0\1\40"+
    "\1\0\1\16\1\24\2\0\1\12\2\0\1\16\2\24"+
    "\1\0\1\12\2\0\1\16\2\24\1\0\1\12\2\0"+
    "\1\41\1\24\2\0\1\12\1\0\1\42\2\24\1\0"+
    "\1\12\1\0\2\24\1\0\1\12\1\43\1\24\2\0"+
    "\1\12\2\24\1\0\1\12\2\24\1\0\1\12\1\24"+
    "\2\0\1\12\2\24\1\0\1\12\2\24\1\0\1\12"+
    "\1\24\2\0\1\12\2\24\1\0\1\12\2\24\1\0"+
    "\1\12\1\24\2\0\1\12\2\24\1\0\1\12\2\24"+
    "\1\0\1\12\1\24\2\0\1\12\2\24\1\0\1\12"+
    "\2\24\1\0\1\12\1\24\2\0\1\12\2\24\1\0"+
    "\1\12\2\24\1\0\1\12\2\0\1\12\1\24\1\0"+
    "\1\12\1\24\2\0\2\24\1\0\2\24\1\0\2\24"+
    "\1\0\2\24\1\0\2\24\1\0\2\24\1\0\2\24"+
    "\1\0\2\24\1\0\2\24\1\0\2\24\1\0\2\24"+
    "\1\0\2\24\1\0\2\24\1\0\2\24\1\0\2\24"+
    "\1\0\2\24\1\0\2\24\1\0\2\24\1\0\1\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[276];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\55\0\132\0\207\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\264\0\55\0\341\0\u010e\0\u013b"+
    "\0\55\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276"+
    "\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\55\0\55\0\55\0\55"+
    "\0\207\0\55\0\u0357\0\u0384\0\u03b1\0\u03de\0\55\0\u040b"+
    "\0\55\0\55\0\55\0\55\0\u0438\0\u0465\0\u0492\0\u04bf"+
    "\0\u01ef\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa"+
    "\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762"+
    "\0\u078f\0\u07bc\0\u07e9\0\u0816\0\55\0\u0843\0\u0870\0\u01ef"+
    "\0\u089d\0\u08ca\0\u08f7\0\u01ef\0\u0924\0\u0951\0\u097e\0\u09ab"+
    "\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u01ef\0\u01ef\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u01ef\0\u0d02\0\u0d2f\0\u0d5c"+
    "\0\u0d89\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4"+
    "\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c"+
    "\0\u1059\0\u1086\0\u10b3\0\u01ef\0\u10e0\0\u110d\0\u113a\0\u1167"+
    "\0\u1194\0\55\0\u11c1\0\u11ee\0\u121b\0\u1248\0\u1275\0\u12a2"+
    "\0\u12cf\0\u12fc\0\u1329\0\55\0\u1356\0\u1383\0\u13b0\0\u13dd"+
    "\0\u140a\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb\0\u1518\0\u1545"+
    "\0\u1572\0\u159f\0\u15cc\0\u15f9\0\u1626\0\u1653\0\u1680\0\u16ad"+
    "\0\u16da\0\u1707\0\u1734\0\u1761\0\u178e\0\u17bb\0\u17e8\0\u1815"+
    "\0\u1842\0\u186f\0\u189c\0\u18c9\0\u18f6\0\u1923\0\u1950\0\u197d"+
    "\0\u19aa\0\u19d7\0\u1a04\0\u1a31\0\u1a5e\0\u1a8b\0\u1ab8\0\u1ae5"+
    "\0\u1b12\0\u1b3f\0\u1b6c\0\u1b99\0\u1bc6\0\u1bf3\0\u1c20\0\u1c4d"+
    "\0\u1c7a\0\u1ca7\0\u1cd4\0\u1d01\0\u1d2e\0\u1d5b\0\u1d88\0\u1db5"+
    "\0\u1de2\0\u1e0f\0\u1e3c\0\u1e69\0\u1e96\0\u1ec3\0\u1ef0\0\u1f1d"+
    "\0\55\0\u1f4a\0\u1f77\0\u1fa4\0\u1fd1\0\u1ffe\0\u202b\0\u2058"+
    "\0\u2085\0\u20b2\0\u20df\0\u0384\0\u210c\0\u2139\0\u2166\0\u2193"+
    "\0\u21c0\0\u21ed\0\u221a\0\u2247\0\u2274\0\u22a1\0\u22ce\0\u22fb"+
    "\0\u2328\0\u2355\0\u2382\0\u23af\0\u23dc\0\u2409\0\u2436\0\u2463"+
    "\0\u2490\0\u24bd\0\u24ea\0\u2517\0\u2544\0\u2571\0\u259e\0\u25cb"+
    "\0\u25f8\0\u2625\0\u2652\0\u267f\0\u26ac\0\u26d9\0\u2706\0\u2733"+
    "\0\u2760\0\u278d\0\u27ba\0\u27e7\0\u2814\0\u2841\0\u286e\0\u289b"+
    "\0\u28c8\0\u28f5\0\u2922\0\u294f\0\u297c\0\u29a9\0\u29d6\0\u2a03"+
    "\0\u2a30\0\u2a5d\0\u2a8a\0\u2a8a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[276];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\25\1\27\1\30"+
    "\3\25\1\31\6\25\1\32\2\25\1\33\1\34\1\35"+
    "\1\36\1\2\1\37\1\40\57\0\1\3\53\0\3\41"+
    "\1\42\10\0\2\41\5\0\24\41\22\0\2\43\51\0"+
    "\1\44\1\0\2\45\51\0\1\44\1\0\2\46\60\0"+
    "\1\47\46\0\1\50\5\0\1\51\1\52\53\0\1\53"+
    "\54\0\1\54\47\0\2\25\5\0\24\25\2\0\1\25"+
    "\17\0\2\25\5\0\4\25\1\55\17\25\2\0\1\25"+
    "\17\0\2\25\5\0\4\25\1\56\17\25\2\0\1\25"+
    "\17\0\2\25\5\0\13\25\1\57\1\25\1\60\6\25"+
    "\2\0\1\25\17\0\2\25\5\0\5\25\1\61\16\25"+
    "\2\0\1\25\17\0\2\25\5\0\20\25\1\62\3\25"+
    "\2\0\1\25\17\0\2\25\5\0\1\63\23\25\2\0"+
    "\1\25\17\0\2\25\5\0\7\25\1\64\14\25\2\0"+
    "\1\25\17\0\2\65\53\0\2\66\51\0\1\44\1\0"+
    "\2\67\51\0\1\44\1\0\2\70\36\0\14\50\1\71"+
    "\4\50\1\0\33\50\15\0\2\25\5\0\6\25\1\72"+
    "\15\25\2\0\1\25\17\0\2\25\5\0\2\25\1\73"+
    "\21\25\2\0\1\25\17\0\2\25\5\0\21\25\1\74"+
    "\2\25\2\0\1\25\17\0\2\25\5\0\3\25\1\75"+
    "\20\25\2\0\1\25\17\0\2\25\5\0\10\25\1\76"+
    "\13\25\2\0\1\25\17\0\2\25\5\0\12\25\1\77"+
    "\11\25\2\0\1\25\17\0\2\25\5\0\10\25\1\100"+
    "\13\25\2\0\1\25\17\0\2\101\53\0\2\102\51\0"+
    "\1\44\1\0\2\103\51\0\1\44\1\0\2\104\61\0"+
    "\1\105\46\0\2\25\5\0\10\25\1\106\13\25\2\0"+
    "\1\25\17\0\2\25\5\0\13\25\1\107\10\25\2\0"+
    "\1\25\17\0\2\25\5\0\4\25\1\110\17\25\2\0"+
    "\1\25\15\0\1\111\1\0\2\25\5\0\3\25\1\112"+
    "\20\25\2\0\1\25\17\0\2\25\5\0\15\25\1\113"+
    "\6\25\2\0\1\25\17\0\2\25\5\0\4\25\1\114"+
    "\17\25\2\0\1\25\17\0\2\25\5\0\13\25\1\115"+
    "\10\25\2\0\1\25\17\0\2\116\51\0\1\117\1\0"+
    "\2\102\51\0\1\44\1\0\2\120\51\0\1\44\1\0"+
    "\2\121\53\0\2\25\5\0\15\25\1\122\6\25\2\0"+
    "\1\25\17\0\2\25\5\0\1\123\23\25\2\0\1\25"+
    "\45\0\1\124\26\0\2\25\5\0\4\25\1\125\17\25"+
    "\2\0\1\25\17\0\2\25\5\0\22\25\1\126\1\25"+
    "\2\0\1\25\17\0\2\25\5\0\4\25\1\127\17\25"+
    "\2\0\1\25\17\0\2\130\53\0\2\131\51\0\1\44"+
    "\1\0\2\132\51\0\1\44\1\0\2\133\51\0\1\134"+
    "\1\0\2\25\5\0\24\25\2\0\1\25\17\0\2\25"+
    "\5\0\20\25\1\135\3\25\2\0\1\25\46\0\1\136"+
    "\25\0\2\25\5\0\2\25\1\137\21\25\2\0\1\25"+
    "\17\0\2\140\53\0\2\141\51\0\1\44\1\0\2\142"+
    "\51\0\1\44\1\0\2\143\101\0\1\144\26\0\2\25"+
    "\5\0\4\25\1\145\17\25\2\0\1\25\44\0\1\146"+
    "\27\0\2\25\5\0\13\25\1\147\10\25\2\0\1\25"+
    "\17\0\2\150\51\0\1\151\1\0\2\141\51\0\1\44"+
    "\1\0\2\152\51\0\1\44\1\0\2\153\102\0\1\154"+
    "\42\0\1\155\37\0\2\25\5\0\1\156\23\25\2\0"+
    "\1\25\17\0\2\157\53\0\2\160\51\0\1\44\1\0"+
    "\2\161\51\0\1\44\1\0\2\162\100\0\1\163\56\0"+
    "\1\164\25\0\2\25\5\0\20\25\1\165\3\25\2\0"+
    "\1\25\17\0\2\166\53\0\2\167\51\0\1\44\1\0"+
    "\2\170\51\0\1\44\1\0\2\171\70\0\1\172\46\0"+
    "\1\173\45\0\2\25\5\0\4\25\1\174\17\25\2\0"+
    "\1\25\17\0\2\175\51\0\1\176\1\0\2\167\51\0"+
    "\1\44\1\0\2\177\51\0\1\44\1\0\2\200\102\0"+
    "\1\201\50\0\1\202\31\0\2\203\53\0\2\204\51\0"+
    "\1\44\1\0\2\205\51\0\1\44\1\0\2\206\62\0"+
    "\1\207\45\0\2\210\53\0\2\211\51\0\1\44\1\0"+
    "\2\212\51\0\1\44\1\0\2\213\76\0\1\214\31\0"+
    "\2\215\51\0\1\216\1\0\2\211\51\0\1\44\1\0"+
    "\2\217\51\0\1\44\1\0\2\220\53\0\2\221\53\0"+
    "\2\222\51\0\1\44\1\0\2\223\51\0\1\44\1\0"+
    "\2\224\53\0\2\225\53\0\2\226\51\0\1\44\1\0"+
    "\2\227\51\0\1\44\1\0\2\230\53\0\2\231\51\0"+
    "\1\232\1\0\2\226\51\0\1\44\1\0\2\233\51\0"+
    "\1\44\1\0\2\234\53\0\2\235\53\0\2\236\51\0"+
    "\1\44\1\0\2\237\51\0\1\44\1\0\2\240\53\0"+
    "\2\241\53\0\2\242\51\0\1\44\1\0\2\243\51\0"+
    "\1\44\1\0\2\244\53\0\2\245\51\0\1\246\1\0"+
    "\2\242\51\0\1\44\1\0\2\247\51\0\1\44\1\0"+
    "\2\250\53\0\2\251\53\0\2\252\51\0\1\44\1\0"+
    "\2\253\51\0\1\44\1\0\2\254\53\0\2\255\53\0"+
    "\2\256\51\0\1\44\1\0\2\257\51\0\1\44\1\0"+
    "\2\260\53\0\2\261\51\0\1\262\1\0\2\256\51\0"+
    "\1\44\1\0\2\263\51\0\1\44\1\0\2\264\53\0"+
    "\2\265\53\0\2\266\51\0\1\44\1\0\2\267\51\0"+
    "\1\44\1\0\2\270\53\0\2\271\53\0\2\272\51\0"+
    "\1\44\1\0\2\273\51\0\1\44\1\0\2\274\53\0"+
    "\2\275\51\0\1\276\1\0\2\272\51\0\1\44\1\0"+
    "\2\277\51\0\1\44\1\0\2\300\53\0\2\301\53\0"+
    "\2\302\51\0\1\44\1\0\2\303\51\0\1\44\1\0"+
    "\2\304\53\0\2\305\53\0\2\306\51\0\1\44\1\0"+
    "\2\307\51\0\1\44\1\0\2\310\53\0\2\311\51\0"+
    "\1\312\1\0\2\306\51\0\1\44\1\0\2\313\51\0"+
    "\1\44\1\0\2\314\53\0\2\315\53\0\2\316\51\0"+
    "\1\44\1\0\2\317\51\0\1\44\1\0\2\320\53\0"+
    "\2\321\53\0\2\322\51\0\1\44\1\0\2\323\51\0"+
    "\1\44\1\0\2\324\51\0\1\325\1\0\2\322\51\0"+
    "\1\44\1\0\2\326\51\0\1\44\1\0\2\327\53\0"+
    "\2\330\51\0\1\44\1\0\2\331\51\0\1\44\1\0"+
    "\2\332\53\0\2\333\51\0\1\334\1\0\2\331\51\0"+
    "\1\334\1\0\2\332\51\0\1\335\1\0\2\333\53\0"+
    "\2\336\53\0\2\337\51\0\1\340\1\0\2\337\53\0"+
    "\2\341\53\0\2\342\51\0\1\343\1\0\2\342\53\0"+
    "\2\344\53\0\2\345\51\0\1\346\1\0\2\345\53\0"+
    "\2\347\53\0\2\350\51\0\1\351\1\0\2\350\53\0"+
    "\2\352\53\0\2\353\51\0\1\354\1\0\2\353\53\0"+
    "\2\355\53\0\2\356\51\0\1\357\1\0\2\356\53\0"+
    "\2\360\53\0\2\361\51\0\1\362\1\0\2\361\53\0"+
    "\2\363\53\0\2\364\51\0\1\365\1\0\2\364\53\0"+
    "\2\366\53\0\2\367\51\0\1\370\1\0\2\367\53\0"+
    "\2\371\53\0\2\372\51\0\1\373\1\0\2\372\53\0"+
    "\2\374\53\0\2\375\51\0\1\376\1\0\2\375\53\0"+
    "\2\377\53\0\2\u0100\51\0\1\u0101\1\0\2\u0100\53\0"+
    "\2\u0102\53\0\2\u0103\51\0\1\u0104\1\0\2\u0103\53\0"+
    "\2\u0105\53\0\2\u0106\51\0\1\u0107\1\0\2\u0106\53\0"+
    "\2\u0108\53\0\2\u0109\51\0\1\u010a\1\0\2\u0109\53\0"+
    "\2\u010b\53\0\2\u010c\51\0\1\u010d\1\0\2\u010c\53\0"+
    "\2\u010e\53\0\2\u010f\51\0\1\u0110\1\0\2\u010f\53\0"+
    "\2\u0111\53\0\2\u0112\51\0\1\u0113\1\0\2\u0112\53\0"+
    "\2\u0114\36\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10935];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\6\11\1\1\1\11\3\1\1\11"+
    "\13\1\4\11\1\0\1\11\2\1\1\0\1\1\1\11"+
    "\1\0\4\11\12\1\1\0\1\1\1\0\11\1\1\0"+
    "\1\1\1\11\3\1\1\0\5\1\2\0\3\1\1\0"+
    "\5\1\1\0\1\1\1\0\1\1\1\0\3\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\2\0\1\1\2\0"+
    "\3\1\1\0\1\1\2\0\3\1\1\0\1\1\2\0"+
    "\2\1\2\0\1\1\1\0\1\11\2\1\1\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\11\1\1\2\0\3\1"+
    "\1\0\3\1\1\0\2\1\2\0\3\1\1\0\3\1"+
    "\1\0\2\1\2\0\3\1\1\0\3\1\1\0\2\1"+
    "\2\0\3\1\1\0\3\1\1\0\2\1\2\0\3\1"+
    "\1\0\3\1\1\0\2\1\2\0\3\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\2\0\2\1\1\0\2\1"+
    "\2\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[276];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

	// Valores maximos
	private final int STR_MAX_LEN = 30;
	/* 2?????*/
	private final int INT_MAX_LEN = 65536;	
	private final float FLOAT_MAX_LEN = 0;
	
	// Tabla de s??mbolos
	private List<Map<Columna, String>> symtbl;
	
	
	// Inicializa la tabla de simbolos
	private void iniTable() {
		TablaSimbolos.escribirArchivo(null, null, false);
		this.symtbl = TablaSimbolos.leerArchivo(null);
	}
	
	
	// Agrega un simbolo de ID de variable
	public void addSym(String nombre, String token, String tipo) {
		boolean encontrado = false;
		int i = 0;
		while (!encontrado && i < symtbl.size()) {
			encontrado = symtbl.get(i).get(Columna.NOMBRE).equals(nombre);
			i++;
		}
		if (!encontrado) {
			Map<Columna, String> sym = new HashMap<Columna, String>();
			sym.put(Columna.NOMBRE, nombre);
			sym.put(Columna.TOKEN, token);
			sym.put(Columna.TIPO, tipo);
			this.symtbl.add(sym);
			TablaSimbolos.escribirArchivo(Arrays.asList(sym), null, true);
		}
	}
	
	
	// Agrega una constante 
	public void addSym(String nombre, String token, String valor, Integer len) {
		boolean encontrado = false;
		int i = 0;
		while (!encontrado && i < symtbl.size()) {
			encontrado = symtbl.get(i).get(Columna.NOMBRE).equals(nombre);
			i++;
		}
		if (!encontrado) {
			Map<Columna,String> sym = new HashMap<Columna, String>();
			sym.put(Columna.NOMBRE, nombre);
			sym.put(Columna.TOKEN, token);
			sym.put(Columna.VALOR, valor);
			if (len != null) sym.put(Columna.LEN, String.valueOf(len));
			this.symtbl.add(sym);
			TablaSimbolos.escribirArchivo(Arrays.asList(sym), null, true);
		}
	}
	
	
	// Verifica la cantidad de bits del integer (0-65535) (recibido como string)
	public boolean checkInt(String s){
		// Verifico que s no este vacia o tenga m??s de 5 digitos
		if (s.isEmpty() || s.length() > 5){
			return false;
		}
		try{
			// Parseo a integer
			Integer number = Integer.valueOf(s);
			// Verifico que no exceda el maximo valor
			if (number > INT_MAX_LEN){
				return false;
			}
		}catch(Exception e){
			System.out.println("Error parseando lexema " + yytext() + ".");
			System.out.println(e.toString());
			return false;
		}	
		return true;
	}
	

	// Verifica la cantidad de bits del float (recibido como string)
	public boolean checkFloat(String s){
		// Verifico que s no este vacia
		if (s.isEmpty()){
			return false;
		}
		try{
			// Parseo a float
			Float number = Float.valueOf(s);
			// Verifico que no exceda el maximo valor
			if (number > FLOAT_MAX_LEN){
				return false;
			}
		}catch(Exception e){
			System.out.println("Error parseando lexema " + yytext() + ".");
			System.out.println(e.toString());
			return false;
		}
		return true;
	}
	
	
	// Verifica que el string no tenga mas de 30 caracteres
	public boolean checkStr(String s){
		if (s.isEmpty() || (s.length() > 30)){
			return false;
		}
		return true;
	}
	
	
	// Imprime cada par token:lexema hallado
	public void anuncio(String token){
		System.out.println("***Nuevo hallazgo***");
		System.out.println("\tToken = " + token + ".\n\tLexema = " + yytext() + ".\n");
	}
	


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolo.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline + " columna " + yycolumn + ".");
            }
            // fall through
          case 36: break;
          case 2:
            { /* no hacer nada */
            }
            // fall through
          case 37: break;
          case 3:
            { anuncio("(");return new Symbol(Simbolo.PAR_ABRE, yycolumn, yyline);
            }
            // fall through
          case 38: break;
          case 4:
            { anuncio(")");return new Symbol(Simbolo.PAR_CIERRA, yycolumn, yyline);
            }
            // fall through
          case 39: break;
          case 5:
            { anuncio("*");return new Symbol(Simbolo.MULTIPLICA, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 40: break;
          case 6:
            { anuncio("+");return new Symbol(Simbolo.SUMA, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 41: break;
          case 7:
            { anuncio(",");return new Symbol(Simbolo.COMA, yycolumn, yyline);
            }
            // fall through
          case 42: break;
          case 8:
            { anuncio("-");return new Symbol(Simbolo.RESTA, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 43: break;
          case 9:
            { anuncio("/");return new Symbol(Simbolo.DIVIDE, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 44: break;
          case 10:
            { if (!checkInt(yytext())){
								System.out.println("Lexema " + yytext() + " excede el valor m??ximo de un Integer (" + INT_MAX_LEN + ").");	
							}
							else{
								anuncio("CONST_INT");
							}
							anuncio("CONST_INT");
							addSym("_" + yytext(), "CONST_INT", yytext(), null);
                            return new Symbol(Simbolo.CONST_INT, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 45: break;
          case 11:
            { anuncio(";");return new Symbol(Simbolo.PUNTO_COMA, yycolumn, yyline);
            }
            // fall through
          case 46: break;
          case 12:
            { anuncio("<");return new Symbol(Simbolo.MENOR, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 47: break;
          case 13:
            { anuncio(">");return new Symbol(Simbolo.MAYOR, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 48: break;
          case 14:
            { anuncio("ID"); addSym(yytext(), "ID", null);
            }
            // fall through
          case 49: break;
          case 15:
            { anuncio("[");return new Symbol(Simbolo.COR_ABRE, yycolumn, yyline);
            }
            // fall through
          case 50: break;
          case 16:
            { anuncio("]");return new Symbol(Simbolo.COR_CIERRA, yycolumn, yyline);
            }
            // fall through
          case 51: break;
          case 17:
            { anuncio("{");return new Symbol(Simbolo.LLAVE_ABRE, yycolumn, yyline);
            }
            // fall through
          case 52: break;
          case 18:
            { anuncio("}");return new Symbol(Simbolo.LLAVE_CIERRA, yycolumn, yyline);
            }
            // fall through
          case 53: break;
          case 19:
            { if (!checkStr(yytext())){
								System.out.println("Lexema " + yytext() + " excede la longitud maxima de un String (" + STR_MAX_LEN + ").");		
							}
							else{
								anuncio("CONST_STR");
							}
							anuncio("CONST_STR");
							addSym("_" + yytext(), "CONST_STR", yytext(), null);
                            return new Symbol(Simbolo.CONST_STR, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 54: break;
          case 20:
            { if (!checkFloat(yytext())){
								System.out.println("Lexema " + yytext() + " excede el valor m??ximo de un Float (" + FLOAT_MAX_LEN + ").");	
							}
							else{
								anuncio("CONST_FLOAT");
							}
							anuncio("CONST_FLOAT");
							addSym("_" + yytext(), "CONST_FLOAT", yytext(), null);
                            return new Symbol(Simbolo.CONST_FLOAT, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 55: break;
          case 21:
            { anuncio(":=");return new Symbol(Simbolo.ASIGNA, yycolumn, yyline);
            }
            // fall through
          case 56: break;
          case 22:
            { anuncio("<=");return new Symbol(Simbolo.MENOR_IGUAL, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 57: break;
          case 23:
            { anuncio("<>");return new Symbol(Simbolo.DISTINTO, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 58: break;
          case 24:
            { anuncio("==");return new Symbol(Simbolo.IGUAL, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 59: break;
          case 25:
            { anuncio(">=");return new Symbol(Simbolo.MAYOR_IGUAL, yycolumn, yyline, new String(yytext()));
            }
            // fall through
          case 60: break;
          case 26:
            { anuncio("IF");return new Symbol(Simbolo.IF, yycolumn, yyline);
            }
            // fall through
          case 61: break;
          case 27:
            { /* se ignora el contenido */
            }
            // fall through
          case 62: break;
          case 28:
            { anuncio("ELSE");return new Symbol(Simbolo.ELSE, yycolumn, yyline);
            }
            // fall through
          case 63: break;
          case 29:
            { anuncio("TAKE");return new Symbol(Simbolo.TAKE, yycolumn, yyline);
            }
            // fall through
          case 64: break;
          case 30:
            { anuncio("PRINT");return new Symbol(Simbolo.PRINT, yycolumn, yyline);
            }
            // fall through
          case 65: break;
          case 31:
            { anuncio("WHILE");return new Symbol(Simbolo.WHILE, yycolumn, yyline);
            }
            // fall through
          case 66: break;
          case 32:
            { anuncio("DECLARE");iniTable(); return new Symbol(Simbolo.DECLARE, yycolumn, yyline);
            }
            // fall through
          case 67: break;
          case 33:
            { anuncio("ENDDECLARE");return new Symbol(Simbolo.ENDDECLARE, yycolumn, yyline);
            }
            // fall through
          case 68: break;
          case 34:
            { anuncio("END.PROGRAM");return new Symbol(Simbolo.END_PROGRAM, yycolumn, yyline);
            }
            // fall through
          case 69: break;
          case 35:
            { anuncio("BEGIN.PROGRAM");return new Symbol(Simbolo.BEGIN_PROGRAM, yycolumn, yyline);
            }
            // fall through
          case 70: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
