// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: entrega_1/01-lexico_entrega_1.flex

package compilador;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.HashMap;
import java.util.Map;


// Para escribir el archivo de la tabla de simbolos
import compilador.TablaSimbolos.*;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\3\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\12\17\1\0\1\20"+
    "\1\21\1\22\1\23\2\0\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\35\1\44\1\45\1\46"+
    "\2\35\1\47\3\35\1\50\1\0\1\51\1\0\1\52"+
    "\1\0\1\53\3\35\1\54\1\55\1\56\1\57\1\60"+
    "\1\35\1\61\1\62\1\35\1\63\1\64\1\65\1\35"+
    "\1\66\1\67\1\70\2\35\1\71\3\35\1\72\1\73"+
    "\1\74\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\3\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\12\17\1\20\1\21\7\17\1\22\1\1\1\23"+
    "\1\0\1\24\1\25\1\0\1\26\1\0\1\27\1\30"+
    "\1\31\1\32\7\17\1\33\12\17\1\34\1\0\7\17"+
    "\1\35\10\17\1\36\2\17\1\37\1\0\5\17\1\40"+
    "\4\17\1\0\1\17\1\41\2\17\1\42\1\0\1\17"+
    "\1\0\1\17\1\0\1\43\1\0\1\17\2\0\1\17"+
    "\2\0\1\17\2\0\1\44\1\0\1\45\1\0\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\75\0\172\0\267\0\364\0\u0131\0\75"+
    "\0\75\0\75\0\75\0\75\0\75\0\u016e\0\75\0\u01ab"+
    "\0\75\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319\0\u0356"+
    "\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4\0\75\0\75"+
    "\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\75"+
    "\0\u06ac\0\75\0\267\0\75\0\75\0\u0131\0\u016e\0\u06e9"+
    "\0\75\0\75\0\75\0\75\0\u0726\0\u0763\0\u07a0\0\u07dd"+
    "\0\u081a\0\u0857\0\u0894\0\u029f\0\u08d1\0\u090e\0\u094b\0\u0988"+
    "\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\75\0\u0b33"+
    "\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde\0\u029f"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6"+
    "\0\75\0\u0f03\0\u0f40\0\u029f\0\u0f7d\0\u0fba\0\u0ff7\0\u1034"+
    "\0\u1071\0\u10ae\0\u029f\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df"+
    "\0\u121c\0\u029f\0\u1259\0\u1296\0\u029f\0\u12d3\0\u1310\0\u134d"+
    "\0\u138a\0\u13c7\0\u029f\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8"+
    "\0\u1535\0\u1572\0\u15af\0\u15ec\0\u1629\0\u029f\0\u1666\0\75"+
    "\0\u16a3\0\75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\25\1\27\1\30"+
    "\1\31\2\25\1\32\6\25\1\33\1\25\1\34\1\35"+
    "\1\36\1\37\1\40\1\2\1\25\1\41\1\42\2\25"+
    "\1\43\4\25\1\44\1\25\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\77\0\1\3\72\0\4\53\1\54\70\53"+
    "\5\0\1\55\67\0\6\56\1\54\66\56\17\0\1\57"+
    "\72\0\1\57\1\0\1\20\73\0\1\60\3\0\1\61"+
    "\1\62\73\0\1\63\74\0\1\64\71\0\1\25\4\0"+
    "\24\25\2\0\20\25\22\0\1\25\4\0\4\25\1\65"+
    "\17\25\2\0\20\25\22\0\1\25\4\0\4\25\1\66"+
    "\17\25\2\0\20\25\22\0\1\25\4\0\13\25\1\67"+
    "\1\25\1\70\6\25\2\0\10\25\1\71\7\25\22\0"+
    "\1\25\4\0\13\25\1\72\10\25\2\0\10\25\1\73"+
    "\7\25\22\0\1\25\4\0\5\25\1\74\7\25\1\75"+
    "\6\25\2\0\3\25\1\74\5\25\1\76\6\25\22\0"+
    "\1\25\4\0\20\25\1\77\3\25\2\0\14\25\1\100"+
    "\3\25\22\0\1\25\4\0\22\25\1\101\1\25\2\0"+
    "\16\25\1\102\1\25\22\0\1\25\4\0\1\103\23\25"+
    "\2\0\1\25\1\104\16\25\22\0\1\25\4\0\7\25"+
    "\1\105\14\25\2\0\5\25\1\106\12\25\22\0\1\25"+
    "\4\0\24\25\2\0\10\25\1\71\7\25\22\0\1\25"+
    "\4\0\24\25\2\0\10\25\1\73\7\25\22\0\1\25"+
    "\4\0\24\25\2\0\3\25\1\74\5\25\1\76\6\25"+
    "\22\0\1\25\4\0\24\25\2\0\14\25\1\100\3\25"+
    "\22\0\1\25\4\0\24\25\2\0\16\25\1\102\1\25"+
    "\22\0\1\25\4\0\24\25\2\0\1\25\1\104\16\25"+
    "\22\0\1\25\4\0\24\25\2\0\5\25\1\106\12\25"+
    "\76\0\1\107\1\0\7\60\2\0\5\60\1\110\4\60"+
    "\1\0\51\60\17\0\1\25\4\0\6\25\1\111\15\25"+
    "\2\0\20\25\22\0\1\25\4\0\2\25\1\112\21\25"+
    "\2\0\20\25\22\0\1\25\4\0\21\25\1\113\2\25"+
    "\2\0\20\25\22\0\1\25\4\0\3\25\1\114\20\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\15\25"+
    "\1\115\2\25\22\0\1\25\4\0\16\25\1\116\5\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\12\25"+
    "\1\117\5\25\22\0\1\25\4\0\22\25\1\120\1\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\16\25"+
    "\1\120\1\25\22\0\1\25\4\0\10\25\1\121\13\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\6\25"+
    "\1\122\11\25\22\0\1\25\4\0\20\25\1\123\3\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\14\25"+
    "\1\124\3\25\22\0\1\25\4\0\12\25\1\125\11\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\7\25"+
    "\1\126\10\25\22\0\1\25\4\0\10\25\1\127\13\25"+
    "\2\0\20\25\22\0\1\25\4\0\24\25\2\0\6\25"+
    "\1\130\11\25\26\0\1\131\70\0\1\25\4\0\10\25"+
    "\1\132\13\25\2\0\20\25\22\0\1\25\4\0\13\25"+
    "\1\133\10\25\2\0\20\25\22\0\1\25\4\0\4\25"+
    "\1\134\17\25\2\0\20\25\20\0\1\135\1\0\1\25"+
    "\4\0\3\25\1\136\20\25\2\0\20\25\22\0\1\25"+
    "\4\0\24\25\2\0\2\25\1\134\15\25\22\0\1\25"+
    "\4\0\1\75\23\25\2\0\20\25\22\0\1\25\4\0"+
    "\24\25\2\0\1\25\1\76\16\25\22\0\1\25\4\0"+
    "\15\25\1\137\6\25\2\0\20\25\22\0\1\25\4\0"+
    "\24\25\2\0\11\25\1\140\6\25\22\0\1\25\4\0"+
    "\10\25\1\141\13\25\2\0\20\25\22\0\1\25\4\0"+
    "\24\25\2\0\6\25\1\142\11\25\22\0\1\25\4\0"+
    "\4\25\1\143\17\25\2\0\20\25\22\0\1\25\4\0"+
    "\24\25\2\0\2\25\1\143\15\25\22\0\1\25\4\0"+
    "\13\25\1\144\10\25\2\0\20\25\22\0\1\25\4\0"+
    "\24\25\2\0\10\25\1\145\7\25\22\0\1\25\4\0"+
    "\15\25\1\146\6\25\2\0\20\25\22\0\1\25\4\0"+
    "\1\147\23\25\2\0\20\25\46\0\1\150\50\0\1\25"+
    "\4\0\4\25\1\151\17\25\2\0\20\25\22\0\1\25"+
    "\4\0\22\25\1\152\1\25\2\0\20\25\22\0\1\25"+
    "\4\0\24\25\2\0\16\25\1\152\1\25\22\0\1\25"+
    "\4\0\15\25\1\153\6\25\2\0\20\25\22\0\1\25"+
    "\4\0\24\25\2\0\11\25\1\154\6\25\22\0\1\25"+
    "\4\0\4\25\1\155\17\25\2\0\20\25\22\0\1\25"+
    "\4\0\24\25\2\0\2\25\1\155\15\25\20\0\1\156"+
    "\1\0\1\25\4\0\24\25\2\0\20\25\22\0\1\25"+
    "\4\0\20\25\1\157\3\25\2\0\20\25\47\0\1\160"+
    "\47\0\1\25\4\0\2\25\1\161\21\25\2\0\20\25"+
    "\22\0\1\25\4\0\6\25\1\120\15\25\2\0\20\25"+
    "\22\0\1\25\4\0\24\25\2\0\4\25\1\120\13\25"+
    "\46\0\1\162\50\0\1\25\4\0\4\25\1\163\17\25"+
    "\2\0\20\25\45\0\1\164\51\0\1\25\4\0\13\25"+
    "\1\165\10\25\2\0\20\25\47\0\1\166\62\0\1\167"+
    "\61\0\1\25\4\0\1\170\23\25\2\0\20\25\45\0"+
    "\1\171\76\0\1\172\47\0\1\25\4\0\20\25\1\173"+
    "\3\25\2\0\20\25\35\0\1\174\66\0\1\175\67\0"+
    "\1\25\4\0\4\25\1\176\17\25\2\0\20\25\47\0"+
    "\1\177\70\0\1\200\60\0\1\201\110\0\1\202\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5856];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\6\11\1\1\1\11\1\1\1\11"+
    "\15\1\2\11\7\1\1\11\1\1\1\11\1\0\2\11"+
    "\1\0\1\1\1\0\4\11\22\1\1\11\1\0\20\1"+
    "\1\11\3\1\1\0\12\1\1\0\5\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\2\0\1\1"+
    "\2\0\1\1\2\0\1\1\1\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

	// Valores maximos
	private final int STR_MAX_LEN = 30;
	/* 2????? */
	private final int INT_MAX_LEN = 65536;	
	/* 2???? */
	private final float FLOAT_MAX_LEN = 0;
	
	// Tabla de s??mbolos
	private List<Map<Columna, String>> symtbl;
	
	
	// Inicializa la tabla de simbolos
	private void iniTable() {
		TablaSimbolos.escribirArchivo(null, null, false);
		this.symtbl = TablaSimbolos.leerArchivo(null);
		EscribeAnalisis.escribir("", false);
	}
	
	

	// Agrega un simbolo de ID de variable
	public void addSym(String nombre, String token, String tipo) {
		boolean encontrado = false;
		int i = 0;
		while (!encontrado && i < symtbl.size()) {
			encontrado = symtbl.get(i).get(Columna.NOMBRE).equals(nombre);
			i++;
		}
		if (!encontrado) {
			Map<Columna, String> sym = new HashMap<Columna, String>();
			sym.put(Columna.NOMBRE, nombre);
			sym.put(Columna.TOKEN, token);
			sym.put(Columna.TIPO, tipo);
			this.symtbl.add(sym);
			TablaSimbolos.escribirArchivo(Arrays.asList(sym), null, true);
		}
	}
	
	
	// Agrega una constante 
	public void addSym(String nombre, String token, String valor, Integer len) {
		boolean encontrado = false;
		int i = 0;
		while (!encontrado && i < symtbl.size()) {
			encontrado = symtbl.get(i).get(Columna.NOMBRE).equals(nombre);
			i++;
		}
		if (!encontrado) {
			Map<Columna,String> sym = new HashMap<Columna, String>();
			sym.put(Columna.NOMBRE, nombre);
			sym.put(Columna.TOKEN, token);
			sym.put(Columna.VALOR, valor);
			if (len != null) sym.put(Columna.LEN, String.valueOf(len));
			this.symtbl.add(sym);
			TablaSimbolos.escribirArchivo(Arrays.asList(sym), null, true);
		}
	}
	
	
	// Verifica la cantidad de bits del integer (0-65535) (recibido como string)
	public boolean checkInt(String s){
		// Verifico que s no este vacia o tenga m??s de 5 digitos
		if (s.isEmpty() || s.length() > 5){
			return false;
		}
		try{
			// Parseo a integer
			Integer number = Integer.valueOf(s);
			// Verifico que no exceda el maximo valor
			if (number > INT_MAX_LEN){
				return false;
			}
		}catch(Exception e){
			System.out.println("Error parseando lexema " + yytext() + ".");
			System.out.println(e.toString());
			return false;
		}	
		return true;
	}
	

	// Verifica la cantidad de bits del float (recibido como string)
	public boolean checkFloat(String s){
		// Verifico que s no este vacia
		if (s.isEmpty()){
			return false;
		}
		try{
			// Parseo a float
			Float number = Float.valueOf(s);
			// Verifico que no exceda el maximo valor
			if (number > FLOAT_MAX_LEN){
				return false;
			}
		}catch(Exception e){
			System.out.println("Error parseando lexema " + yytext() + ".");
			System.out.println(e.toString());
			return false;
		}
		return true;
	}

	
	
	// Verifica que el string no tenga mas de 30 caracteres
	public boolean checkStr(String s){
		if (s.isEmpty() || (s.length() > 30)){
			return false;
		}
		return true;
	}
	
	
	// Imprime cada par token:lexema hallado
	public void anuncio(String token){
		System.out.println("***Nuevo hallazgo***");
		System.out.println("\tToken = " + token + "\n\tLexema = '" + yytext() + "'\n");
		EscribeAnalisis.escribir("***Nuevo hallazgo***", true);
		EscribeAnalisis.escribir("\tToken = " + token + "\n\tLexema = '" + yytext() + "'\n", true);
	}
	


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline + " columna " + yycolumn + ".");
            }
            // fall through
          case 39: break;
          case 2:
            { /* no hacer nada */
            }
            // fall through
          case 40: break;
          case 3:
            { anuncio("PAR_ABRE");
            }
            // fall through
          case 41: break;
          case 4:
            { anuncio("PAR_CIERRA");
            }
            // fall through
          case 42: break;
          case 5:
            { anuncio("MULTIPLICA");
            }
            // fall through
          case 43: break;
          case 6:
            { anuncio("SUMA");
            }
            // fall through
          case 44: break;
          case 7:
            { anuncio("COMA");
            }
            // fall through
          case 45: break;
          case 8:
            { anuncio("RESTA");
            }
            // fall through
          case 46: break;
          case 9:
            { anuncio("DIVIDE");
            }
            // fall through
          case 47: break;
          case 10:
            { anuncio("CONST_INT");					
							if (!checkInt(yytext())){
								System.out.println("Lexema " + yytext() + " excede el valor maximo de un Integer (" + INT_MAX_LEN + ").\n");	
							}
							else{
								addSym("_" + yytext(), "CONST_INT", yytext(), null);
							}
            }
            // fall through
          case 48: break;
          case 11:
            { anuncio("PUNTO_COMA");
            }
            // fall through
          case 49: break;
          case 12:
            { anuncio("MENOR");
            }
            // fall through
          case 50: break;
          case 13:
            { anuncio("ASIGNA");
            }
            // fall through
          case 51: break;
          case 14:
            { anuncio("MAYOR");
            }
            // fall through
          case 52: break;
          case 15:
            { anuncio("ID_VAR"); addSym(yytext(), "ID_VAR", null);
            }
            // fall through
          case 53: break;
          case 16:
            { anuncio("COR_ABRE");
            }
            // fall through
          case 54: break;
          case 17:
            { anuncio("COR_CIERRA");
            }
            // fall through
          case 55: break;
          case 18:
            { anuncio("LLAVE_ABRE");
            }
            // fall through
          case 56: break;
          case 19:
            { anuncio("LLAVE_CIERRA");
            }
            // fall through
          case 57: break;
          case 20:
            { anuncio("CONST_STR");
							if (!checkStr(yytext())){
								System.out.println("Lexema " + yytext() + " excede la longitud maxima de un String (" + STR_MAX_LEN + ").\n");		
							}
							else{
								addSym("_" + yytext(), "CONST_STR", yytext(), yytext().length());
							}
            }
            // fall through
          case 58: break;
          case 21:
            { anuncio("AND");
            }
            // fall through
          case 59: break;
          case 22:
            { anuncio("CONST_FLOAT");
							if (!checkFloat(yytext())){
								System.out.println("Lexema " + yytext() + " excede el valor maximo de un Float (" + FLOAT_MAX_LEN + ").\n");	
							}
							else{
								addSym("_" + yytext(), "CONST_FLOAT", yytext(), null);
							}
            }
            // fall through
          case 60: break;
          case 23:
            { anuncio("MENOR_IGUAL");
            }
            // fall through
          case 61: break;
          case 24:
            { anuncio("DISTINTO");
            }
            // fall through
          case 62: break;
          case 25:
            { anuncio("IGUAL");
            }
            // fall through
          case 63: break;
          case 26:
            { anuncio("MAYOR_IGUAL");
            }
            // fall through
          case 64: break;
          case 27:
            { anuncio("IF");
            }
            // fall through
          case 65: break;
          case 28:
            { anuncio("OR");
            }
            // fall through
          case 66: break;
          case 29:
            { anuncio("TIPO_DATO");
            }
            // fall through
          case 67: break;
          case 30:
            { anuncio("COMENTARIO");
            }
            // fall through
          case 68: break;
          case 31:
            { anuncio("ELSE");
            }
            // fall through
          case 69: break;
          case 32:
            { anuncio("TAKE");
            }
            // fall through
          case 70: break;
          case 33:
            { anuncio("PRINT");
            }
            // fall through
          case 71: break;
          case 34:
            { anuncio("WHILE");
            }
            // fall through
          case 72: break;
          case 35:
            { anuncio("DECLARE");iniTable();
            }
            // fall through
          case 73: break;
          case 36:
            { anuncio("ENDDECLARE");
            }
            // fall through
          case 74: break;
          case 37:
            { anuncio("END.PROGRAM");
            }
            // fall through
          case 75: break;
          case 38:
            { anuncio("BEGIN.PROGRAM");
            }
            // fall through
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
