// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexico.flex

import java_cup.runtime.Symbol;



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\24\0\1\4"+
    "\5\0\1\5\1\6\2\7\1\0\1\7\1\10\1\11"+
    "\1\12\11\13\1\14\1\15\1\16\1\17\1\20\2\0"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\32\1\41\1\42\1\43\2\32\1\44\3\32\1\45"+
    "\1\0\1\46\1\0\1\47\1\0\4\32\1\50\1\51"+
    "\1\32\1\52\1\53\2\32\1\54\1\32\1\55\1\32"+
    "\1\56\1\32\1\57\1\60\1\61\2\32\1\62\3\32"+
    "\u0185\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\3\1\1\3\2\1\14\4\1\0"+
    "\1\5\1\0\1\6\1\7\1\0\5\4\1\10\5\4"+
    "\2\0\12\4\1\0\1\11\2\4\1\12\1\0\3\4"+
    "\1\13\2\4\1\0\2\4\1\0\1\4\1\14\1\15"+
    "\2\0\1\4\1\0\1\4\3\0\1\4\1\0\1\4"+
    "\1\16\1\0\1\17\1\0\1\4\2\0\1\4\2\0"+
    "\1\4\1\0\1\20\1\21\1\0\1\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\63\0\146\0\231\0\314\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\231\0\63"+
    "\0\u042f\0\377\0\63\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e"+
    "\0\u0561\0\u01cb\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b"+
    "\0\u085e\0\u0891\0\u08c4\0\u08f7\0\63\0\u092a\0\u095d\0\u01cb"+
    "\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u01cb\0\u0a5c\0\u0a8f\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u01cb\0\u01cb\0\u0bc1\0\u0bf4"+
    "\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c"+
    "\0\u0dbf\0\63\0\u0df2\0\63\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe"+
    "\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\63\0\63\0\u0ff0"+
    "\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\2\2\1\7\1\2"+
    "\2\10\1\11\1\2\1\12\2\2\1\13\1\14\1\13"+
    "\1\15\1\16\3\13\1\17\6\13\1\20\2\13\1\21"+
    "\1\22\3\2\1\23\2\13\1\24\2\13\1\25\3\13"+
    "\1\26\65\0\1\3\61\0\3\27\1\30\5\0\2\27"+
    "\5\0\24\27\3\0\13\27\7\0\1\31\1\0\1\31"+
    "\63\0\2\32\57\0\1\32\1\0\2\10\66\0\1\33"+
    "\54\0\1\34\63\0\2\13\5\0\24\13\2\0\14\13"+
    "\12\0\2\13\5\0\4\13\1\35\17\13\2\0\14\13"+
    "\12\0\2\13\5\0\4\13\1\36\17\13\2\0\14\13"+
    "\12\0\2\13\5\0\13\13\1\37\1\13\1\40\6\13"+
    "\2\0\5\13\1\41\6\13\12\0\2\13\5\0\5\13"+
    "\1\42\16\13\2\0\2\13\1\42\11\13\12\0\2\13"+
    "\5\0\20\13\1\43\3\13\2\0\10\13\1\44\3\13"+
    "\12\0\2\13\5\0\1\45\23\13\2\0\14\13\12\0"+
    "\2\13\5\0\7\13\1\46\14\13\2\0\3\13\1\47"+
    "\10\13\12\0\2\13\5\0\24\13\2\0\5\13\1\41"+
    "\6\13\12\0\2\13\5\0\24\13\2\0\2\13\1\42"+
    "\11\13\12\0\2\13\5\0\24\13\2\0\10\13\1\44"+
    "\3\13\12\0\2\13\5\0\24\13\2\0\3\13\1\47"+
    "\10\13\15\0\1\50\45\0\11\34\1\51\4\34\1\0"+
    "\44\34\12\0\2\13\5\0\6\13\1\52\15\13\2\0"+
    "\14\13\12\0\2\13\5\0\2\13\1\53\21\13\2\0"+
    "\14\13\12\0\2\13\5\0\21\13\1\54\2\13\2\0"+
    "\14\13\12\0\2\13\5\0\3\13\1\55\20\13\2\0"+
    "\14\13\12\0\2\13\5\0\24\13\2\0\11\13\1\56"+
    "\2\13\12\0\2\13\5\0\10\13\1\57\13\13\2\0"+
    "\14\13\12\0\2\13\5\0\24\13\2\0\4\13\1\60"+
    "\7\13\12\0\2\13\5\0\12\13\1\61\11\13\2\0"+
    "\14\13\12\0\2\13\5\0\10\13\1\62\13\13\2\0"+
    "\14\13\12\0\2\13\5\0\24\13\2\0\4\13\1\63"+
    "\7\13\13\0\1\64\67\0\1\65\54\0\2\13\5\0"+
    "\10\13\1\66\13\13\2\0\14\13\12\0\2\13\5\0"+
    "\13\13\1\67\10\13\2\0\14\13\12\0\2\13\5\0"+
    "\4\13\1\70\17\13\2\0\14\13\10\0\1\71\1\0"+
    "\2\13\5\0\3\13\1\72\20\13\2\0\14\13\12\0"+
    "\2\13\5\0\24\13\2\0\1\13\1\70\12\13\12\0"+
    "\2\13\5\0\15\13\1\73\6\13\2\0\14\13\12\0"+
    "\2\13\5\0\24\13\2\0\6\13\1\74\5\13\12\0"+
    "\2\13\5\0\4\13\1\75\17\13\2\0\14\13\12\0"+
    "\2\13\5\0\13\13\1\76\10\13\2\0\14\13\12\0"+
    "\2\13\5\0\24\13\2\0\5\13\1\77\6\13\15\0"+
    "\1\100\57\0\2\13\5\0\15\13\1\101\6\13\2\0"+
    "\14\13\12\0\2\13\5\0\1\102\23\13\2\0\14\13"+
    "\40\0\1\103\34\0\2\13\5\0\4\13\1\104\17\13"+
    "\2\0\14\13\12\0\2\13\5\0\22\13\1\105\1\13"+
    "\2\0\14\13\12\0\2\13\5\0\24\13\2\0\12\13"+
    "\1\105\1\13\12\0\2\13\5\0\4\13\1\106\17\13"+
    "\2\0\14\13\12\0\2\13\5\0\24\13\2\0\1\13"+
    "\1\106\12\13\45\0\1\107\25\0\1\110\1\0\2\13"+
    "\5\0\24\13\2\0\14\13\12\0\2\13\5\0\20\13"+
    "\1\111\3\13\2\0\14\13\41\0\1\112\33\0\2\13"+
    "\5\0\2\13\1\113\21\13\2\0\14\13\12\0\2\114"+
    "\32\0\1\115\54\0\1\116\34\0\2\13\5\0\4\13"+
    "\1\117\17\13\2\0\14\13\37\0\1\120\35\0\2\13"+
    "\5\0\13\13\1\121\10\13\2\0\14\13\15\0\1\107"+
    "\53\0\1\122\115\0\1\123\33\0\2\13\5\0\24\13"+
    "\1\0\1\124\14\13\27\0\1\125\45\0\2\13\5\0"+
    "\1\126\23\13\2\0\14\13\37\0\1\127\64\0\1\130"+
    "\33\0\2\13\5\0\20\13\1\131\3\13\2\0\14\13"+
    "\27\0\1\132\54\0\1\133\53\0\2\13\5\0\4\13"+
    "\1\134\17\13\2\0\14\13\41\0\1\135\56\0\1\136"+
    "\37\0\2\13\5\0\24\13\1\0\1\137\14\13\21\0"+
    "\1\140\76\0\1\141\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4131];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\23\1\1\0\1\11\1\0\1\1\1\11"+
    "\1\0\13\1\2\0\12\1\1\0\1\11\3\1\1\0"+
    "\6\1\1\0\2\1\1\0\3\1\2\0\1\1\1\0"+
    "\1\1\3\0\1\1\1\0\1\1\1\11\1\0\1\11"+
    "\1\0\1\1\2\0\1\1\2\0\1\1\1\0\2\11"+
    "\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

	// Valores maximos
	private final int STR_MAX_LEN = 30
	private final Integer INT_MAX_LEN = 65536		/* 2?????*/
	private final Float FLOAT_MAX_LEN = 4294967296 	/* 2????*/
	
	
	// Tabla de simbolos
	// Lista de mapas con NOMBRE | TOKEN | TIPO | VALOR | LONGITUD
	private List<Map<Columna, String>> symTable;
	
	
	// Inicializo mapa
	private void iniTable(){
		symTable = new List<Map<Columna, String>>();
	
	}
	
	
	// Agrega el token encontrado como simbolo
	public void addSymbol(){
	
	}
	
	// Verifica la cantidad de bits del integer (recibido como string)
	public boolean checkInt(String s){
		// Verifico que s no este vacia
		if (s.isEmpty()){
			return false;
		}
		try{
			// Parseo a integer
			Integer number = Integer.valueOf(s)
			// Verifico que no exceda el maximo valor
			if (number > INT_MAX_VALUE){
				return false;
			}
		}catch(Exception e){
			System.out.println("Error parseando lexema " + yytext() + ".");
			System.out.println(e.toString());
			return false;
		}	
		return true;
	}
	
	
	
	// Verifica la cantidad de bits del float (recibido como string)
	public booolean checkFloat(String s){
		// Verifico que s no este vacia
		if (s.isEmpty()){
			return false;
		}
		try{
			// Parseo a float
			Float number = Float.valueOf(s)
			// Verifico que no exceda el maximo valor
			if (number > FLOAT_MAX_VALUE){
				return false;
			}
		}catch(Exception e){
			System.out.println("Error parseando lexema " + yytext() + ".");
			System.out.println(e.toString());
			return false;
		}
		return true;
	}
	
	
	// Verifica que el string no tenga mas de 30 caracteres
	public boolean checkStr(String s){
		if (s.isEmpty() || (s.length() > 30)){
			return false;
		}
		return true;
	}
	
	
	// Imprime cada par token:lexema hallado
	public void anuncio(String token){
		System.out.println("***Nuevo hallazgo***")
		System.out.println("\tToken = " + token + ".\n\tLexema = " + yytext() + ".\n");
	}
	


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline + " columna " + yycolumn + ".");
            }
            // fall through
          case 19: break;
          case 2:
            { /* no hacer nada */
            }
            // fall through
          case 20: break;
          case 3:
            { if !(checkInt(yytext())){
							System.out.println("Lexema " + yytext() + " excede el valor m??ximo de un Integer (" + INT_MAX_LEN + ").");	
						}
						else{
							anuncio("CONST_INT");
						}
            }
            // fall through
          case 21: break;
          case 4:
            { anuncio("ID_VAR");
            }
            // fall through
          case 22: break;
          case 5:
            { if !(checkStr(yytext())){
							System.out.println("Lexema " + yytext() + " excede la longitud maxima de un String (" + STR_MAX_LEN + ").");		
						}
						else{
							anuncio("CONST_STR");
						}
            }
            // fall through
          case 23: break;
          case 6:
            { if !(checkFloat(yytext())){
							System.out.println("Lexema " + yytext() + " excede el valor m??ximo de un Float (" + FLOAT_MAX_LEN + ").");	
						}
						else{
							anuncio("CONST_FLOAT");
						}
            }
            // fall through
          case 24: break;
          case 7:
            { anuncio("ASIGNACION");
            }
            // fall through
          case 25: break;
          case 8:
            { anuncio("IF");
            }
            // fall through
          case 26: break;
          case 9:
            { /* se ignora el contenido */
            }
            // fall through
          case 27: break;
          case 10:
            { anuncio("ELSE");
            }
            // fall through
          case 28: break;
          case 11:
            { anuncio("TAKE");
            }
            // fall through
          case 29: break;
          case 12:
            { anuncio("PRINT");
            }
            // fall through
          case 30: break;
          case 13:
            { anuncio("WHILE");
            }
            // fall through
          case 31: break;
          case 14:
            { anuncio("TAKE_CUERPO");
            }
            // fall through
          case 32: break;
          case 15:
            { anuncio("DECLARE");
            }
            // fall through
          case 33: break;
          case 16:
            { anuncio("END.PROGRAM");
            }
            // fall through
          case 34: break;
          case 17:
            { anuncio("ENDDECLARE");
            }
            // fall through
          case 35: break;
          case 18:
            { anuncio("BEGIN.PROGRAM");iniTable();
            }
            // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
